"""
Django settings for biota_site project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from biota_shifts.env_manual import load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_path = BASE_DIR / ".env"
_secrets_path = BASE_DIR / ".env.secrets"
load_env_file(_env_path)
load_env_file(_secrets_path)
try:
    from dotenv import load_dotenv

    # override=True: значения из .env перекрывают устаревший BIOTA_* в окружении ОС/IDE
    load_dotenv(_env_path, override=True)
    # Секреты поверх .env (пароли, SECRET_KEY)
    load_dotenv(_secrets_path, override=True)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-&j#7pt+-7u0y)n&ihg(og#(x-3^yn^ax449c7e_d!r4&cbxbsx",
)

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = (os.getenv("DJANGO_DEBUG") or "").strip().lower()
DEBUG = _debug_env not in ("0", "false", "no") if _debug_env else True

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

_csrf_raw = (os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS") or "").strip()
CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_raw.split(",") if x.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shifts",
    "regulations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "shifts.middleware.ExecutorReadOnlyMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "biota_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shifts.context_processors.biota_session",
            ],
        },
    },
]

WSGI_APPLICATION = "biota_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_site_db_host = (os.getenv("SITE_DB_HOST") or "").strip()
if _site_db_host:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("SITE_DB_NAME", "site_db"),
            "USER": os.getenv("SITE_DB_USER", "site_user"),
            "PASSWORD": os.getenv("SITE_DB_PASSWORD", ""),
            "HOST": _site_db_host,
            "PORT": os.getenv("SITE_DB_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("SITE_DB_CONN_MAX_AGE", "0") or "0"),
            "OPTIONS": {
                "connect_timeout": int(os.getenv("SITE_DB_CONNECT_TIMEOUT", "15") or "15"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Куда копировать статику для продакшена: `manage.py collectstatic` → Nginx раздаёт этот каталог как /static/
STATIC_ROOT = BASE_DIR / "staticfiles"

# Загрузки изделий (чертежи, CAD). При DEBUG файлы отдаёт Django; в проде настройте раздачу /media/ через nginx.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Иначе <object>/<iframe> с PDF с того же сайта часто блокируются при значении по умолчанию DENY.
X_FRAME_OPTIONS = "SAMEORIGIN"

# Раздавать /media/ через Django при DEBUG или если явно DJANGO_SERVE_MEDIA=1 (например gunicorn без nginx).
SERVE_MEDIA_FROM_DJANGO = (os.getenv("DJANGO_SERVE_MEDIA") or "").strip().lower() in ("1", "true", "yes")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"

# Табель графика: много полей (сотрудники × дни месяца)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Те же переменные, что и у Streamlit-приложения (PostgreSQL Biota, пароль admin и т.д.)
BIOTA_DB_HOST = os.getenv("BIOTA_DB_HOST", "localhost")
BIOTA_DB_PORT = os.getenv("BIOTA_DB_PORT", "5432")
BIOTA_DB_NAME = os.getenv("BIOTA_DB_NAME", "biota_db")
BIOTA_DB_USER = os.getenv("BIOTA_DB_USER", "biota_user")
BIOTA_DB_PASSWORD = os.getenv("BIOTA_DB_PASSWORD", "")
BIOTA_DB_CONNECT_TIMEOUT = os.getenv("BIOTA_DB_CONNECT_TIMEOUT", "15")
BIOTA_ADMIN_USERNAME = os.getenv("BIOTA_ADMIN_USERNAME", "admin")
BIOTA_ADMIN_PASSWORD = os.getenv("BIOTA_ADMIN_PASSWORD", "")
BIOTA_AUTH_COOKIE_SECRET = os.getenv("BIOTA_AUTH_COOKIE_SECRET", "")
BIOTA_USERS_STORE = os.getenv("BIOTA_USERS_STORE", "")
BIOTA_SCHEDULE_DIR = os.getenv("BIOTA_SCHEDULE_DIR", "")
