"""
Django settings for biota_site project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from biota_shifts.config import biota_db_env
from biota_shifts.env_manual import load_env_file
from biota_site.perf_flags import load_perf_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_env_path = BASE_DIR / ".env"
_secrets_path = BASE_DIR / ".env.secrets"
load_env_file(_env_path)
load_env_file(_secrets_path)
try:
    from dotenv import load_dotenv

    # override=True: значения из .env перекрывают устаревший BIOTA_* в окружении ОС/IDE
    load_dotenv(_env_path, override=True)
    # Секреты поверх .env (пароли, SECRET_KEY)
    load_dotenv(_secrets_path, override=True)
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-&j#7pt+-7u0y)n&ihg(og#(x-3^yn^ax449c7e_d!r4&cbxbsx",
)

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = (os.getenv("DJANGO_DEBUG") or "").strip().lower()
DEBUG = _debug_env not in ("0", "false", "no") if _debug_env else True

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

_csrf_raw = (os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS") or "").strip()
CSRF_TRUSTED_ORIGINS = [x.strip() for x in _csrf_raw.split(",") if x.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shifts",
    "regulations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "shifts.middleware.AuthRateLimitMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "shifts.middleware.ExecutorReadOnlyMiddleware",
    "shifts.middleware.PerfDiagnosticMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "biota_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shifts.context_processors.biota_session",
            ],
        },
    },
]

WSGI_APPLICATION = "biota_site.wsgi.application"

_rl_disabled = (os.getenv("BIOTA_REGISTER_RATELIMIT") or "1").strip().lower() in ("0", "false", "no")
BIOTA_REGISTER_RATELIMIT_ENABLED = not _rl_disabled
BIOTA_REGISTER_RATELIMIT_BURST = int(os.getenv("BIOTA_REGISTER_RATELIMIT_BURST", "30") or "30")
BIOTA_REGISTER_RATELIMIT_BURST_WINDOW = int(os.getenv("BIOTA_REGISTER_RATELIMIT_BURST_WINDOW", "300") or "300")
BIOTA_REGISTER_RATELIMIT_POST = int(os.getenv("BIOTA_REGISTER_RATELIMIT_POST", "5") or "5")
BIOTA_REGISTER_RATELIMIT_POST_WINDOW = int(os.getenv("BIOTA_REGISTER_RATELIMIT_POST_WINDOW", "3600") or "3600")

_login_rl_disabled = (os.getenv("BIOTA_LOGIN_RATELIMIT") or "1").strip().lower() in ("0", "false", "no")
BIOTA_LOGIN_RATELIMIT_ENABLED = not _login_rl_disabled
BIOTA_LOGIN_RATELIMIT_MAX = int(os.getenv("BIOTA_LOGIN_RATELIMIT_MAX", "10") or "10")
BIOTA_LOGIN_RATELIMIT_WINDOW = int(os.getenv("BIOTA_LOGIN_RATELIMIT_WINDOW", "900") or "900")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "biota-default",
    },
    "ratelimit": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / ".cache" / "ratelimit",
        "OPTIONS": {"MAX_ENTRIES": 10000},
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_site_db_host = (os.getenv("SITE_DB_HOST") or "").strip()
if _site_db_host:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("SITE_DB_NAME", "site_db"),
            "USER": os.getenv("SITE_DB_USER", "site_user"),
            "PASSWORD": os.getenv("SITE_DB_PASSWORD", ""),
            "HOST": _site_db_host,
            "PORT": os.getenv("SITE_DB_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("SITE_DB_CONN_MAX_AGE", "0") or "0"),
            "OPTIONS": {
                "connect_timeout": int(os.getenv("SITE_DB_CONNECT_TIMEOUT", "15") or "15"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Куда копировать статику для продакшена: `manage.py collectstatic` → Nginx раздаёт этот каталог как /static/
STATIC_ROOT = BASE_DIR / "staticfiles"
# Увеличивайте после правок CSS/JS, чтобы браузер и nginx не отдавали старые файлы.
STATIC_ASSET_VERSION = (os.getenv("STATIC_ASSET_VERSION") or "134").strip() or "134"

# Оптимизации производительности (пакет A): по умолчанию выключены. См. PERFORMANCE_NOTES.md и .env.example.
_perf = load_perf_settings()
BIOTA_PERF_PACKAGE_A = _perf["BIOTA_PERF_PACKAGE_A"]
BIOTA_PERF_MOBILE_GRAPH = _perf["BIOTA_PERF_MOBILE_GRAPH"]
BIOTA_PERF_DEFER_SCRIPTS = _perf["BIOTA_PERF_DEFER_SCRIPTS"]
BIOTA_PERF_USERS_STORE_CACHE_SEC = _perf["BIOTA_PERF_USERS_STORE_CACHE_SEC"]
BIOTA_PERF_DIAGNOSTICS = _perf["BIOTA_PERF_DIAGNOSTICS"]
BIOTA_PERF_DIAG_TTFB_MS = _perf["BIOTA_PERF_DIAG_TTFB_MS"]
BIOTA_PERF_DIAG_LOAD_MS = _perf["BIOTA_PERF_DIAG_LOAD_MS"]
BIOTA_PERF_DIAG_SERVER_MS = _perf["BIOTA_PERF_DIAG_SERVER_MS"]
BIOTA_PERF_DIAG_KEEP = _perf["BIOTA_PERF_DIAG_KEEP"]

# Загрузки изделий (чертежи, CAD). При DEBUG файлы отдаёт Django; в проде настройте раздачу /media/ через nginx.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Иначе <object>/<iframe> с PDF с того же сайта часто блокируются при значении по умолчанию DENY.
X_FRAME_OPTIONS = "SAMEORIGIN"

# Раздавать /media/ через Django при DEBUG или если явно DJANGO_SERVE_MEDIA=1 (например gunicorn без nginx).
SERVE_MEDIA_FROM_DJANGO = (os.getenv("DJANGO_SERVE_MEDIA") or "").strip().lower() in ("1", "true", "yes")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/home/"

# Табель графика: много полей (сотрудники × дни месяца)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Те же переменные, что и у Streamlit-приложения (PostgreSQL Biota, пароль admin и т.д.)
BIOTA_DB_HOST = biota_db_env("HOST", "localhost")
BIOTA_DB_PORT = biota_db_env("PORT", "5432")
BIOTA_DB_NAME = biota_db_env("NAME", "biota_db")
BIOTA_DB_USER = biota_db_env("USER", "biota_user")
BIOTA_DB_PASSWORD = biota_db_env("PASSWORD", "")
BIOTA_DB_CONNECT_TIMEOUT = biota_db_env("CONNECT_TIMEOUT", "15")
BIOTA_ADMIN_USERNAME = os.getenv("BIOTA_ADMIN_USERNAME", "admin")
BIOTA_ADMIN_PASSWORD = os.getenv("BIOTA_ADMIN_PASSWORD", "")
BIOTA_AUTH_COOKIE_SECRET = os.getenv("BIOTA_AUTH_COOKIE_SECRET", "")
BIOTA_USERS_STORE = os.getenv("BIOTA_USERS_STORE", "")
BIOTA_SCHEDULE_DIR = os.getenv("BIOTA_SCHEDULE_DIR", "")
BIOTA_SITE_URL = (os.getenv("BIOTA_SITE_URL") or "").strip()

# Почта: подтверждение регистрации. Без SMTP в DEBUG письма в консоль runserver.
_email_backend = (os.getenv("DJANGO_EMAIL_BACKEND") or "").strip()
if not _email_backend:
    _email_backend = (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    )
EMAIL_BACKEND = _email_backend
EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("DJANGO_EMAIL_PORT", "587") or "587")
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = (os.getenv("DJANGO_EMAIL_USE_TLS") or "1").strip().lower() not in ("0", "false", "no")
EMAIL_USE_SSL = (os.getenv("DJANGO_EMAIL_USE_SSL") or "").strip().lower() in ("1", "true", "yes")
EMAIL_TIMEOUT = int(os.getenv("DJANGO_EMAIL_TIMEOUT", "15") or "15")
DEFAULT_FROM_EMAIL = os.getenv("DJANGO_DEFAULT_FROM_EMAIL", "noreply@biota.local")
