# Generated by Django 5.2.13 on 2026-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegulationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_date", models.DateField()),
                ("employee_code", models.CharField(db_index=True, max_length=64)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("position", models.CharField(blank=True, default="", max_length=255)),
                (
                    "shift",
                    models.CharField(
                        choices=[("д", "Дневная"), ("н", "Ночная")],
                        default="д",
                        max_length=1,
                    ),
                ),
                ("breakfast_start", models.TimeField()),
                ("breakfast_end", models.TimeField()),
                ("lunch_start", models.TimeField()),
                ("lunch_end", models.TimeField()),
            ],
            options={
                "ordering": ["employee_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan_date", "employee_code"),
                        name="uniq_regulation_employee_per_day",
                    )
                ],
            },
        ),
    ]
