# Generated by Django 5.2.13 on 2026-04-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_remove_regulationplan_is_smoker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationplan',
            name='eight_hour_shift',
            field=models.BooleanField(default=False, help_text='8-часовая смена: один перерыв на питание вместо двух.'),
        ),
        migrations.AlterField(
            model_name='regulationplan',
            name='locked',
            field=models.BooleanField(default=False, help_text='Закрепить строку: нельзя случайно сдвинуть время на шкале.'),
        ),
    ]
