# Generated by Django 5.2.13 on 2026-04-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('end_mill', 'Фреза'), ('tap', 'Метчик')], max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=180, verbose_name='Наименование')),
                ('tool_material', models.CharField(blank=True, max_length=80, verbose_name='Материал инструмента')),
                ('work_material', models.CharField(blank=True, max_length=120, verbose_name='Материал обработки')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструмент',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TapSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_standard', models.CharField(choices=[('metric', 'Метрическая (M)'), ('unc', 'UNC'), ('unf', 'UNF'), ('unef', 'UNEF'), ('bsp', 'BSP'), ('npt', 'NPT'), ('other', 'Другое')], default='metric', max_length=20)),
                ('size_label', models.CharField(max_length=32, verbose_name='Размер (M2, 1/4-20 и т.д.)')),
                ('pitch_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Шаг резьбы, мм')),
                ('tpi', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='TPI (для дюймовых)')),
                ('hole_type', models.CharField(choices=[('through', 'Сквозное'), ('blind', 'Глухое'), ('any', 'Универсальное')], default='any', max_length=16)),
                ('tap_type', models.CharField(choices=[('cutting', 'Режущий метчик'), ('forming', 'Метчик-раскатник'), ('thread_mill', 'Резьбофреза')], default='cutting', max_length=20)),
                ('overall_length_mm', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Общая длина, мм')),
                ('cutting_length_mm', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Длина реж. части, мм')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tap_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры метчика',
                'verbose_name_plural': 'Параметры метчиков',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('issue', 'Выдача'), ('restock', 'Пополнение')], max_length=16, verbose_name='Тип операции')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('employee_name', models.CharField(blank=True, max_length=120, verbose_name='Сотрудник')),
                ('movement_date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'ordering': ('-movement_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EndMillSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_mm', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Диаметр, мм')),
                ('overall_length_mm', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Общая длина, мм')),
                ('cutting_length_mm', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Длина реж. части, мм')),
                ('flutes_count', models.PositiveSmallIntegerField(verbose_name='Количество кромок')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_mill_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры фрезы',
                'verbose_name_plural': 'Параметры фрез',
            },
        ),
    ]
