# Generated by Django 5.2.13 on 2026-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент')], max_length=20, verbose_name='Категория'),
        ),
    ]
