# Generated by Django 5.2.13 on 2026-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_alter_toolitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='endmillspec',
            name='mill_type',
            field=models.CharField(choices=[('end', 'Концевая фреза'), ('roughing', 'Обдирочная фреза'), ('t_slot', 'Т-образная фреза')], default='end', max_length=20, verbose_name='Тип фрезы'),
        ),
    ]
