# Generated by Django 5.2.13 on 2026-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_endmillspec_mill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endmillspec',
            name='cutting_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина реж. части, мм'),
        ),
        migrations.AlterField(
            model_name='endmillspec',
            name='diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Диаметр, мм'),
        ),
        migrations.AlterField(
            model_name='endmillspec',
            name='flutes_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество кромок'),
        ),
        migrations.AlterField(
            model_name='endmillspec',
            name='overall_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Общая длина, мм'),
        ),
        migrations.AlterField(
            model_name='tapspec',
            name='cutting_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина реж. части, мм'),
        ),
        migrations.AlterField(
            model_name='tapspec',
            name='overall_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Общая длина, мм'),
        ),
    ]
