# Generated by Django 5.2.13 on 2026-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_endmillspec_cutting_length_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolitem',
            name='coating_type',
            field=models.CharField(choices=[('yellow', 'Желтое'), ('brown', 'Коричневое'), ('black', 'Черное'), ('none', 'Без покрытия'), ('multicolor', 'Цветное'), ('blue', 'Синее'), ('other', 'Другое')], default='none', max_length=20, verbose_name='Материал покрытия'),
        ),
    ]
