# Generated by Django 5.2.13 on 2026-04-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_toolitem_coating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='tool_material',
            field=models.CharField(blank=True, choices=[('hss', 'HSS'), ('hss_co', 'HSS-Co'), ('carbide', 'Твердосплав')], max_length=80, verbose_name='Материал инструмента'),
        ),
        migrations.AlterField(
            model_name='toolitem',
            name='work_material',
            field=models.CharField(blank=True, choices=[('P', 'P (синий) — углеродистые и легированные стали'), ('M', 'M (жёлтый) — нержавеющие стали'), ('K', 'K (красный) — чугун'), ('N', 'N (зелёный) — цветные металлы'), ('S', 'S (коричневый) — жаропрочные сплавы и титан'), ('H', 'H (серый) — закалённые стали (45–65 HRC)')], max_length=120, verbose_name='Материал обработки'),
        ),
    ]
