# Generated by Django 5.2.13 on 2026-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_toolitem_tool_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endmillspec',
            name='corner_radius_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Радиус, мм'),
        ),
    ]
