# Generated by Django 5.2.13 on 2026-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_endmillspec_corner_radius_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('issue', 'Выдача'), ('restock', 'Пополнение'), ('writeoff', 'Списание')], max_length=16, verbose_name='Тип операции'),
        ),
    ]
