# Generated by Django 5.2.13 on 2026-04-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='parent_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_outcomes', to='shifts.stockmovement', verbose_name='Исходная выдача'),
        ),
    ]
