# Generated by Django 5.2.13 on 2026-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_stockmovement_parent_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_item', models.CharField(max_length=255, verbose_name='Что закупить')),
                ('store_link', models.URLField(blank=True, verbose_name='Ссылка на магазин')),
                ('article', models.CharField(blank=True, max_length=120, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('ordered', 'Заказано'), ('delivered', 'Доставлено'), ('stocked', 'Реализовано на складе')], default='processing', max_length=20, verbose_name='Статус')),
                ('request_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий к заявке')),
                ('status_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий по статусу')),
                ('requested_by', models.CharField(max_length=120, verbose_name='Кто запросил')),
                ('status_updated_by', models.CharField(blank=True, max_length=120, verbose_name='Кто сменил статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
