# Generated by Django 5.2.13 on 2026-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_purchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за 1 шт'),
        ),
    ]
