# Generated by Django 5.2.13 on 2026-04-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_purchaserequest_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDefectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_date', models.DateField(verbose_name='Дата')),
                ('responsible_name', models.CharField(max_length=120, verbose_name='Ответственный')),
                ('employee_name', models.CharField(db_index=True, max_length=120, verbose_name='Сотрудник')),
                ('defect_quantity', models.PositiveIntegerField(verbose_name='Кол-во брака')),
                ('good_quantity', models.PositiveIntegerField(default=0, verbose_name='Исправно')),
                ('bad_quantity', models.PositiveIntegerField(default=0, verbose_name='Неисправно')),
                ('defect_reason', models.CharField(max_length=500, verbose_name='Причина брака')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Косяк сотрудника',
                'verbose_name_plural': 'Косяки сотрудников',
                'ordering': ('-defect_date', '-id'),
            },
        ),
    ]
