# Generated by Django 5.2.13 on 2026-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_employeedefectrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedefectrecord',
            name='department_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Отдел'),
        ),
    ]
