# Generated by Django 5.2.13 on 2026-04-27 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0024_alter_productsetup_tool_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cad_model',
            field=models.FileField(blank=True, help_text='Скачивание; для STP/STEP в окне — отдельный STL ниже.', upload_to='products/cad/', validators=[django.core.validators.FileExtensionValidator(['stl', 'stp', 'step'])], verbose_name='3D-модель (STL, STP, STEP)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_stl',
            field=models.FileField(blank=True, help_text='Сетка для 3D в карточке; для STP/STEP — экспорт в STL сюда.', upload_to='products/preview_stl/', validators=[django.core.validators.FileExtensionValidator(['stl'])], verbose_name='STL для предпросмотра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='program_file',
            field=models.FileField(blank=True, upload_to='products/programs/', verbose_name='Программа (G/M, любой файл)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='setup_notes',
            field=models.TextField(blank=True, default='', help_text='Заготовка, привязка, инструмент, прочее.', verbose_name='Наладка (текст)'),
        ),
    ]
