# Generated by Django 5.2.13 on 2026-04-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0027_productsetup_workpiece_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedefectrecord',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Изделие'),
        ),
    ]
