# Generated by Django 5.2.13 on 2026-04-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0028_employeedefectrecord_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSetupToolRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "tool_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Номер"
                    ),
                ),
                (
                    "kor_n",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Кор. н"
                    ),
                ),
                (
                    "kor_d",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Кор. д"
                    ),
                ),
                (
                    "tool_type",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Тип"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=180,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "diameter",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Диаметр"
                    ),
                ),
                (
                    "overhang",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Вылет"
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="shifts.productsetup",
                        verbose_name="Установка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка инструмента",
                "verbose_name_plural": "Строки инструмента",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
