# Generated by Django 5.2.13 on 2026-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0029_productsetuptoolrow"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsetuptoolrow",
            name="tap_hole_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Метчик: тип отверстия",
            ),
        ),
    ]
