# Generated by Django 5.2.13 on 2026-04-29 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0030_productsetuptoolrow_tap_hole_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetup',
            name='preview_stl',
            field=models.FileField(blank=True, upload_to='products/setup_preview_stl/', validators=[django.core.validators.FileExtensionValidator(['stl'])], verbose_name='STL предпросмотра установки'),
        ),
    ]
