# Generated by Django 5.2.13 on 2026-04-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0032_productsetup_gcode_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='CenterDrillSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Диаметр, мм')),
                ('overall_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина, мм')),
                ('angle_deg', models.CharField(choices=[('60', '60'), ('90', '90'), ('120', '120')], default='60', max_length=8, verbose_name='Угол, °')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_drill_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры центровки',
                'verbose_name_plural': 'Параметры центровок',
            },
        ),
    ]
