# Generated by Django 5.2.13 on 2026-04-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0033_alter_toolitem_category_centerdrillspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='CountersinkSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countersink_type', models.CharField(choices=[('hand', 'Ручной'), ('machine', 'Машинный')], default='machine', max_length=16, verbose_name='Тип зенкера')),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Диаметр, мм')),
                ('angle_deg', models.CharField(choices=[('60', '60'), ('75', '75'), ('90', '90'), ('120', '120')], default='90', max_length=8, verbose_name='Угол, °')),
                ('overall_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина, мм')),
                ('flutes_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество кромок')),
                ('size_label', models.CharField(blank=True, max_length=32, verbose_name='Размер')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='countersink_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры зенкера',
                'verbose_name_plural': 'Параметры зенкеров',
            },
        ),
    ]
