# Generated by Django 5.2.13 on 2026-04-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0034_alter_toolitem_category_countersinkspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.CreateModel(
            name="DrillSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Диаметр, мм",
                    ),
                ),
                (
                    "overall_length_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Длина, мм",
                    ),
                ),
                (
                    "cutting_length_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Длина реж. части, мм",
                    ),
                ),
                (
                    "angle_deg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Угол, °",
                    ),
                ),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drill_spec",
                        to="shifts.toolitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметры сверла",
                "verbose_name_plural": "Параметры сверл",
            },
        ),
    ]
