# Generated by Django 5.2.13 on 2026-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0035_alter_toolitem_category_drillspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endmillspec",
            name="mill_type",
            field=models.CharField(
                choices=[
                    ("end", "Концевая фреза"),
                    ("roughing", "Обдирочная фреза"),
                    ("t_slot", "Т-образная фреза"),
                    ("radius", "Радиусная фреза"),
                    ("ball", "Сферическая фреза"),
                ],
                default="end",
                max_length=20,
                verbose_name="Тип фрезы",
            ),
        ),
    ]
