# Generated by Django 5.2.13 on 2026-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0036_alter_endmillspec_mill_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Удален"),
        ),
        migrations.AddField(
            model_name="toolitem",
            name="deleted_by",
            field=models.CharField(blank=True, max_length=120, verbose_name="Удалил"),
        ),
        migrations.AddField(
            model_name="toolitem",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Помечен как удаленный"
            ),
        ),
    ]
