# Generated by Django 5.2.13 on 2026-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0037_toolitem_deleted_at_toolitem_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='created_by_account',
            field=models.CharField(blank=True, max_length=120, verbose_name='Кто выполнил'),
        ),
    ]
