# Generated by Django 5.2.13 on 2026-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0038_stockmovement_created_by_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolitem',
            name='main_diameter_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Основной диаметр зажима, мм'),
        ),
    ]
