# Generated by Django 5.2.13 on 2026-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0039_toolitem_main_diameter_mm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='work_material',
            field=models.CharField(blank=True, choices=[('P', 'P (синий) — углеродистые и легированные стали'), ('M', 'M (жёлтый) — нержавеющие стали'), ('K', 'K (красный) — чугун'), ('N', 'N (зелёный) — цветные металлы'), ('S', 'S (коричневый) — жаропрочные сплавы и титан'), ('H', 'H (серый) — закалённые стали (45–65 HRC)'), ('PW', 'Пластик (белый)')], max_length=120, verbose_name='Материал обработки'),
        ),
    ]
