# Generated by Django 5.2.13 on 2026-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0040_work_material_plastic_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='tool_material',
            field=models.CharField(blank=True, choices=[('hrc55', 'HRC 55'), ('hrc60', 'HRC 60'), ('hrc65', 'HRC 65'), ('hss', 'HSS'), ('hss_co', 'HSS-Co'), ('carbide', 'Твердосплав')], max_length=80, verbose_name='Материал инструмента'),
        ),
    ]
