# Generated by Django 5.2.13 on 2026-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0041_expand_tool_material_hrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='coating_type',
            field=models.CharField(choices=[('none', 'Без покрытия'), ('yellow', 'Желтое'), ('brown', 'Коричневое'), ('black', 'Черное'), ('multicolor', 'Цветное'), ('blue', 'Синее'), ('other', 'Другое')], default='none', max_length=20, verbose_name='Материал покрытия'),
        ),
    ]
