# Generated by Django 5.2.13 on 2026-05-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0042_reorder_coating_none_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='tool_material',
            field=models.CharField(blank=True, choices=[('hrc45', 'HRC 45'), ('hrc50', 'HRC 50'), ('hrc55', 'HRC 55'), ('hrc60', 'HRC 60'), ('hrc65', 'HRC 65'), ('hrc66', 'HRC 66'), ('hrc70', 'HRC 70'), ('hrc75', 'HRC 75'), ('hrc80', 'HRC 80'), ('hss', 'HSS'), ('hss_co', 'HSS-Co'), ('carbide', 'Твердосплав')], max_length=80, verbose_name='Материал инструмента'),
        ),
    ]
