# Generated by Django 5.2.13 on 2026-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0043_tool_material_more_hrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Код сотрудника (Biota)')),
                ('hourly_rate_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ставка дневная, ₽/ч')),
                ('hourly_rate_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ставка ночная, ₽/ч')),
                ('shift_hours', models.PositiveSmallIntegerField(choices=[(8, '8 часов'), (10, '10 часов'), (12, '12 часов')], default=8, verbose_name='Длительность смены, ч')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.CharField(blank=True, default='', max_length=200, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Параметры ЗП сотрудника',
                'verbose_name_plural': 'Параметры ЗП сотрудников',
            },
        ),
    ]
