# Generated by Django 5.2.13 on 2026-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0044_employee_payroll_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(db_index=True, max_length=128, verbose_name='Код сотрудника')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('tab_by_day', models.JSONField(blank=True, default=dict, verbose_name='Часы по табелю по дням (ISO дата → часы)')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Премия, % от начисления по табелю')),
                ('bonus_rub', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Премия, ₽')),
                ('penalty_quality_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Штраф «качество», % от табеля')),
                ('penalty_result_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Штраф «результат», % от табеля')),
                ('penalty_mode_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Штраф «режим», % от табеля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.CharField(blank=True, default='', max_length=200, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Расчёт ЗП за месяц',
                'verbose_name_plural': 'Расчёты ЗП за месяц',
                'constraints': [models.UniqueConstraint(fields=('emp_code', 'year', 'month'), name='uniq_employee_payroll_settlement_ym')],
            },
        ),
    ]
