# Generated by Django 5.2.13 on 2026-05-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0053_productsetupprogramfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название изделия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Изделие (план)',
                'verbose_name_plural': 'Изделия (план)',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PlannedProductStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('department', models.CharField(choices=[('Заготовительная', 'Заготовительная'), ('Лазерный', 'Лазерный'), ('Гибочный', 'Гибочный'), ('Фрезерный', 'Фрезерный'), ('Токарный', 'Токарный'), ('Гальваника', 'Гальваника'), ('РТИ', 'РТИ'), ('Грязная слесарка', 'Грязная слесарка'), ('Женская слесарка', 'Женская слесарка'), ('Покраска', 'Покраска'), ('Маркировка', 'Маркировка'), ('Сборка', 'Сборка')], max_length=120, verbose_name='Отдел')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание этапа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='shifts.plannedproduct')),
            ],
            options={
                'verbose_name': 'Этап изделия (план)',
                'verbose_name_plural': 'Этапы изделия (план)',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
