# Generated by Django 5.2.13 on 2026-05-06 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0054_planned_product_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='is_assembly',
            field=models.BooleanField(default=False, help_text='Если да — задаётся состав из других изделий плана.', verbose_name='Сборочное изделие'),
        ),
        migrations.CreateModel(
            name='PlannedAssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_components', to='shifts.plannedproduct', verbose_name='Сборочное изделие')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shifts.plannedproduct', verbose_name='Входит в состав')),
            ],
            options={
                'verbose_name': 'Позиция состава (план)',
                'verbose_name_plural': 'Позиции состава (план)',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('assembly', 'component'), name='uniq_planned_assembly_component_pair')],
            },
        ),
    ]
