# Generated by Django 5.2.13 on 2026-05-06 22:01

from django.db import migrations


def forwards_slesarka(apps, schema_editor):
    Stage = apps.get_model("shifts", "PlannedProductStage")
    Stage.objects.filter(department="Грязная слесарка").update(department="Слесарка")
    Stage.objects.filter(department="Женская слесарка").update(department="Слесарка")


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0055_planned_assembly_bom'),
    ]

    operations = [
        migrations.RunPython(forwards_slesarka, migrations.RunPython.noop),
    ]
