# Generated by Django 5.2.13 on 2026-05-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0056_collapse_planned_slesarka_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedassemblycomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Сколько единиц входящего изделия на одну сборочную единицу.', verbose_name='Кол-во на 1 комплект'),
        ),
        migrations.AlterField(
            model_name='plannedproductstage',
            name='department',
            field=models.CharField(choices=[('Заготовительная', 'Заготовительная'), ('Лазерный', 'Лазерный'), ('Гибочный', 'Гибочный'), ('Фрезерный', 'Фрезерный'), ('Токарный', 'Токарный'), ('Гальваника', 'Гальваника'), ('РТИ', 'РТИ'), ('ПКИ', 'ПКИ (закупка, без изготовления)'), ('Слесарка', 'Слесарка'), ('Покраска', 'Покраска'), ('Маркировка', 'Маркировка'), ('Сборка', 'Сборка')], max_length=120, verbose_name='Отдел'),
        ),
    ]
