# Generated by Django 5.2.13 on 2026-05-06 22:13

from django.db import migrations, models


def forwards_pki_stage_to_flag(apps, schema_editor):
    Stage = apps.get_model("shifts", "PlannedProductStage")
    Product = apps.get_model("shifts", "PlannedProduct")
    pki_product_ids = set(Stage.objects.filter(department="ПКИ").values_list("product_id", flat=True))
    if pki_product_ids:
        Product.objects.filter(pk__in=pki_product_ids).update(is_purchased=True)
    Stage.objects.filter(department="ПКИ").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0057_planned_assembly_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='is_purchased',
            field=models.BooleanField(default=False, help_text='Закупная позиция без собственного изготовления на площадке; маршрут по отделам не обязателен.', verbose_name='Покупное изделие'),
        ),
        migrations.RunPython(forwards_pki_stage_to_flag, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='plannedproductstage',
            name='department',
            field=models.CharField(choices=[('Заготовительная', 'Заготовительная'), ('Лазерный', 'Лазерный'), ('Гибочный', 'Гибочный'), ('Фрезерный', 'Фрезерный'), ('Токарный', 'Токарный'), ('Гальваника', 'Гальваника'), ('РТИ', 'РТИ'), ('Слесарка', 'Слесарка'), ('Покраска', 'Покраска'), ('Маркировка', 'Маркировка'), ('Сборка', 'Сборка')], max_length=120, verbose_name='Отдел'),
        ),
    ]
