# Generated by Django 5.2.13 on 2026-05-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0058_planned_purchased_flag_and_drop_pki_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='workpiece_type',
            field=models.CharField(blank=True, choices=[('preparatory', 'Заготовительный'), ('laser', 'Лазерный'), ('pki', 'ПКИ')], default='', help_text='Только для обычного изделия: с какого направления поступает заготовка (для планирования по отделам).', max_length=20, verbose_name='Тип заготовки'),
        ),
    ]
