# Generated by Django 5.2.13 on 2026-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0059_planned_product_workpiece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedproductstage',
            name='department',
            field=models.CharField(choices=[('Заготовительная', 'Заготовительная'), ('Лазерный', 'Лазерный'), ('Гибочный', 'Гибочный'), ('Сварочный', 'Сварочный'), ('Фрезерный', 'Фрезерный'), ('Токарный', 'Токарный'), ('Гальваника', 'Гальваника'), ('РТИ', 'РТИ'), ('Слесарка', 'Слесарка'), ('Покраска', 'Покраска'), ('Маркировка', 'Маркировка'), ('Сборка', 'Сборка')], max_length=120, verbose_name='Отдел'),
        ),
    ]
