# Generated by Django 5.2.13 on 2026-05-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0060_planned_department_svarchnyy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='laser_material_marking',
            field=models.CharField(blank=True, default='', help_text='Для заготовки с лазера: маркировка листа/материала.', max_length=240, verbose_name='Маркировка материала (лазер)'),
        ),
        migrations.AddField(
            model_name='plannedproduct',
            name='laser_sheet_thickness_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Толщина листа (лазер), мм'),
        ),
    ]
