# Generated by Django 5.2.13 on 2026-05-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0061_planned_product_laser_sheet_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Необязательно.', max_length=320, verbose_name='Примечание')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контракт (план)',
                'verbose_name_plural': 'Контракты (план)',
                'ordering': ('deadline', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PlanContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shifts.plancontract', verbose_name='Контракт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shifts.plannedproduct', verbose_name='Позиция плана')),
            ],
            options={
                'verbose_name': 'Строка контракта',
                'verbose_name_plural': 'Строки контракта',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
