# Generated by Django 5.2.13 on 2026-05-06 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0062_plan_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='naladki_product',
            field=models.OneToOneField(blank=True, help_text='Обычное изделие плана синхронизируется одна-к-одному с карточкой наладки (не ПКИ и не сборка).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_piece', to='shifts.product', verbose_name='Карточка в наладках'),
        ),
    ]
