# Generated by Django 5.2.13 on 2026-05-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0066_product_drawing_blank_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_username",
                    models.CharField(max_length=150, verbose_name="Автор (логин)"),
                ),
                ("body", models.TextField(max_length=4000, verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="shifts.product",
                        verbose_name="Изделие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка к изделию",
                "verbose_name_plural": "Заметки к изделию",
                "ordering": ("created_at", "id"),
            },
        ),
    ]
