# Generated by Django 5.2.13 on 2026-05-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0067_product_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productnote",
            options={
                "ordering": ("created_at", "id"),
                "verbose_name": "Заметка к изделию / установке",
                "verbose_name_plural": "Заметки к изделию / установкам",
            },
        ),
        migrations.AddField(
            model_name="productnote",
            name="setup",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — заметки ко вкладке «Изделие»; иначе — к указанной установке.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="shifts.productsetup",
                verbose_name="Установка",
            ),
        ),
    ]
