# Generated by Django 5.2.13 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0071_alter_productsetup_gcode_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='tool_material',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Материал инструмента'),
        ),
    ]
