# Generated by Django 5.2.13 on 2026-05-13 15:50

import shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0074_machinesboardstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsetup',
            name='binding_extra_blocks',
            field=models.JSONField(blank=True, default=shifts.models._default_binding_extra_blocks, help_text='Список объектов {binding_x, binding_y, binding_z, gcode_system}; основной блок — в полях выше.', verbose_name='Дополнительные блоки привязок (X/Y/Z/G)'),
        ),
    ]
