# Generated by Django 5.2.13 on 2026-05-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0076_employeedefectrecord_record_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("drawing", "Чертёж (PDF)"),
                            ("cad_model", "3D-модель (STL/STP/STEP)"),
                            ("cad_step", "STP/STEP"),
                            ("program", "Программа (G/M-код)"),
                            ("tool_spec", "Инструментальная спецификация"),
                            ("photo", "Фото"),
                            ("custom", "Другое"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Допускается любой тип файла.",
                        upload_to="products/files/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        help_text="Если пусто, используется имя загруженного файла.",
                        max_length=255,
                        verbose_name="Отображаемое имя",
                    ),
                ),
                (
                    "original_field_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Для обратной совместимости (drawing_pdf, cad_model, etc.). Внутреннее использование.",
                        max_length=50,
                        verbose_name="Исходное поле",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="shifts.product",
                        verbose_name="Изделие",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если указана, файл относится к конкретной наладке. Если пусто — файл уровня изделия.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="shifts.productsetup",
                        verbose_name="Наладка (опционально)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл изделия",
                "verbose_name_plural": "Файлы изделия",
                "ordering": ("sort_order", "created_at", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("original_field_name__gt", "")),
                        fields=("product", "setup", "original_field_name"),
                        name="unique_product_file_legacy_field",
                    )
                ],
            },
        ),
    ]
