# Generated by Django 5.2.13 on 2026-05-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0077_productfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedproduct',
            name='workpiece_size',
            field=models.CharField(blank=True, default='', help_text='Размеры заготовки для ленточной пилы или ПКИ (например: 10x10x10).', max_length=100, verbose_name='Размер заготовки'),
        ),
        migrations.AddField(
            model_name='plannedproduct',
            name='workpiece_type_enum',
            field=models.CharField(blank=True, default='', help_text='Тип заготовки для ленточной пилы (заготовительный, валиковый и т.д.).', max_length=50, verbose_name='Тип заготовки'),
        ),
    ]
