# Generated by Django 5.2.13 on 2026-05-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0082_productdrawingfile_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='InsertSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_shape', models.CharField(choices=[('C', 'C — ромб 80°'), ('D', 'D — ромб 55°'), ('H', 'H — шестигранник'), ('K', 'K — параллелограмм 55°'), ('L', 'L — прямоугольник'), ('M', 'M — ромб 86°'), ('O', 'O — восьмиугольник'), ('P', 'P — пятиугольник'), ('R', 'R — круглая'), ('S', 'S — квадрат'), ('T', 'T — треугольник'), ('V', 'V — ромб 35°'), ('W', 'W — треугольник 80° (W)')], default='C', max_length=1, verbose_name='Форма (ISO)')),
                ('relief_angle', models.CharField(choices=[('N', 'N — 0°'), ('A', 'A — 3°'), ('B', 'B — 5°'), ('C', 'C — 7°'), ('P', 'P — 11°'), ('D', 'D — 15°'), ('E', 'E — 20°'), ('F', 'F — 25°'), ('G', 'G — 30°'), ('O', 'O — 10°')], default='N', max_length=1, verbose_name='Задний угол')),
                ('tolerance_class', models.CharField(choices=[('M', 'M — средний'), ('G', 'G — точный'), ('E', 'E — точный (E)'), ('U', 'U — грубый'), ('F', 'F — точный (F)')], default='M', max_length=1, verbose_name='Допуск')),
                ('mounting_chip', models.CharField(choices=[('N', 'N — без отверстия'), ('G', 'G — с отверстием, стружколом'), ('M', 'M — с отверстием'), ('A', 'A — с отверстием, односторонний СЛ'), ('W', 'W — с отверстием, паз'), ('T', 'T — с отверстием, односторонний'), ('Q', 'Q — с отверстием, двусторонний'), ('X', 'X — специальное')], default='G', max_length=1, verbose_name='Крепление / СЛ')),
                ('cutting_edge_length_code', models.CharField(blank=True, default='', max_length=2, verbose_name='Код длины кромки')),
                ('cutting_edge_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина кромки, мм')),
                ('thickness_code', models.CharField(blank=True, default='', max_length=2, verbose_name='Код толщины')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Толщина, мм')),
                ('nose_radius_code', models.CharField(blank=True, default='', max_length=2, verbose_name='Код R вершины')),
                ('nose_radius_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='R вершины, мм')),
                ('iso_designation', models.CharField(blank=True, default='', max_length=32, verbose_name='Маркировка ISO')),
                ('milling_family', models.CharField(blank=True, choices=[('', '— не указано —'), ('APKT', 'APKT — пластина 80°'), ('APHT', 'APHT'), ('ADKT', 'ADKT'), ('SEKT', 'SEKT'), ('SEHT', 'SEHT'), ('SNHT', 'SNHT'), ('SPGT', 'SPGT'), ('SPHT', 'SPHT'), ('RPMT', 'RPMT'), ('R390', 'R390'), ('CNMG', 'CNMG (токарная)'), ('WNMG', 'WNMG (токарная)'), ('TNMG', 'TNMG (токарная)'), ('SNMG', 'SNMG (токарная)'), ('CCMT', 'CCMT'), ('DCMT', 'DCMT'), ('VCMT', 'VCMT'), ('OTHER', 'Другое')], default='', max_length=24, verbose_name='Семейство')),
                ('chipbreaker_grade', models.CharField(blank=True, default='', max_length=40, verbose_name='Стужколом / сплав')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insert_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры пластины',
                'verbose_name_plural': 'Параметры пластин',
            },
        ),
    ]
