# Generated by Django 5.2.13 on 2026-05-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0085_insertspec_machining_application_multi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertspec',
            name='milling_family',
            field=models.CharField(blank=True, choices=[('', '— не указано —'), ('APKT', 'APKT — пластина 80°'), ('APMT', 'APMT'), ('APHT', 'APHT'), ('ADKT', 'ADKT'), ('SEKT', 'SEKT'), ('SEHT', 'SEHT'), ('SNHT', 'SNHT'), ('SPGT', 'SPGT'), ('SPHT', 'SPHT'), ('RPMT', 'RPMT'), ('R390', 'R390'), ('CNMG', 'CNMG (токарная)'), ('WNMG', 'WNMG (токарная)'), ('TNMG', 'TNMG (токарная)'), ('SNMG', 'SNMG (токарная)'), ('CCMT', 'CCMT'), ('DCMT', 'DCMT'), ('VCMT', 'VCMT'), ('OTHER', 'Другое')], default='', max_length=24, verbose_name='Семейство'),
        ),
    ]
