# Generated by Django 5.2.13 on 2026-05-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0086_alter_insertspec_milling_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги')], max_length=20, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='ColletSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collet_type', models.CharField(choices=[('er', 'ER'), ('er_g', 'ER G'), ('ers', 'ERS'), ('eoc', 'EOC'), ('sc', 'SC'), ('sk', 'SK'), ('threading', 'Резьбонарезная'), ('cc', 'CC'), ('dc', 'DC'), ('phc_hc', 'PHC/HC'), ('ter', 'TER')], max_length=16, verbose_name='Тип цанги')),
                ('er_size', models.CharField(blank=True, default='', max_length=8, verbose_name='Размер ER')),
                ('clamp_range', models.CharField(blank=True, default='', max_length=16, verbose_name='Диапазон зажима')),
                ('high_precision_aa', models.BooleanField(default=False, verbose_name='Высокоточная (AA)')),
                ('square_size', models.CharField(blank=True, default='', max_length=16, verbose_name='Квадрат, мм')),
                ('thread_standard', models.CharField(blank=True, default='', max_length=16, verbose_name='Стандарт резьбы')),
                ('thread_size_label', models.CharField(blank=True, default='', max_length=32, verbose_name='Размер резьбы')),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Диаметр, мм')),
                ('size_label', models.CharField(blank=True, default='', max_length=64, verbose_name='Параметры')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collet_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры цанги',
                'verbose_name_plural': 'Параметры цанг',
            },
        ),
    ]
