# Generated by Django 5.2.13 on 2026-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0087_collet_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colletspec',
            name='thread_standard',
            field=models.CharField(blank=True, choices=[('iso529', 'ISO 529'), ('din371', 'DIN 371'), ('din376', 'DIN 376'), ('iso', 'ISO'), ('jis', 'JIS')], default='', max_length=16, verbose_name='Стандарт резьбы'),
        ),
    ]
