# Generated by Django 5.2.13 on 2026-05-27

from django.db import migrations, models


def _map_iso529_to_iso(apps, schema_editor):
    ColletSpec = apps.get_model("shifts", "ColletSpec")
    ColletSpec.objects.filter(thread_standard="iso529").update(thread_standard="iso")


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0088_alter_colletspec_thread_standard"),
    ]

    operations = [
        migrations.AddField(
            model_name="colletspec",
            name="threading_series",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tc820", "TC820"),
                    ("gt12", "GT12"),
                    ("gt24", "GT24"),
                    ("gt42", "GT42"),
                    ("gt12_die", "GT12 под плашки"),
                    ("tc820_die", "TC820 под плашки"),
                ],
                default="",
                max_length=16,
                verbose_name="Серия",
            ),
        ),
        migrations.AddField(
            model_name="colletspec",
            name="threading_use",
            field=models.CharField(
                blank=True,
                choices=[("tap", "Для метчиков"), ("die", "Для плашек")],
                default="",
                max_length=8,
                verbose_name="Назначение",
            ),
        ),
        migrations.RunPython(_map_iso529_to_iso, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="colletspec",
            name="thread_standard",
            field=models.CharField(
                blank=True,
                choices=[
                    ("din371", "DIN 371"),
                    ("din376", "DIN 376"),
                    ("iso", "ISO"),
                    ("jis", "JIS"),
                    ("ns", "NS"),
                    ("fes", "FES"),
                ],
                default="",
                max_length=16,
                verbose_name="Стандарт резьбы",
            ),
        ),
    ]
