# Generated by Django 5.2.13 on 2026-05-27

from django.db import migrations, models


_ER_G_SQUARE_TO_INNER = {
    "2.8x2.8": "2.8",
    "3x3": "3",
    "3.15x3.15": "3.15",
    "3.5x3.5": "3.5",
    "3.55x3.55": "3.55",
    "4x4": "4",
    "4.5x4.5": "4.5",
    "5x5": "5",
    "5.5x5.5": "5.5",
    "6x6": "6",
    "6.2x6.2": "6.2",
    "6.3x6.3": "6.3",
    "7x7": "7",
    "8x8": "8",
    "9x9": "9",
    "10x10": "10",
    "11x11": "11",
    "11.2x11.2": "11.2",
    "12x12": "12",
    "12.5x12.5": "12.5",
    "13x13": "13",
    "15x15": "15",
    "17x17": "17",
}


def _migrate_er_g_inner_from_square(apps, schema_editor):
    ColletSpec = apps.get_model("shifts", "ColletSpec")
    for spec in ColletSpec.objects.filter(collet_type="er_g").exclude(square_size=""):
        sq = (spec.square_size or "").strip().lower()
        inner = _ER_G_SQUARE_TO_INNER.get(sq, "")
        if inner and not spec.inner_diameter:
            spec.inner_diameter = inner
            spec.save(update_fields=["inner_diameter"])


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0089_colletspec_threading_series_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="colletspec",
            name="inner_diameter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2.8", "2,8"),
                    ("3", "3"),
                    ("3.15", "3,15"),
                    ("3.5", "3,5"),
                    ("3.55", "3,55"),
                    ("4", "4"),
                    ("4.5", "4,5"),
                    ("5", "5"),
                    ("5.5", "5,5"),
                    ("6", "6"),
                    ("6.2", "6,2"),
                    ("6.3", "6,3"),
                    ("7", "7"),
                    ("8", "8"),
                    ("8.5", "8,5"),
                    ("9", "9"),
                    ("10", "10"),
                    ("10.5", "10,5"),
                    ("11", "11"),
                    ("11.2", "11,2"),
                    ("12", "12"),
                    ("12.5", "12,5"),
                    ("13", "13"),
                    ("14", "14"),
                    ("15", "15"),
                    ("16", "16"),
                    ("17", "17"),
                    ("18", "18"),
                    ("19", "19"),
                    ("20", "20"),
                    ("2-13", "2–13"),
                    ("2-16", "2–16"),
                    ("3-10", "3–10"),
                    ("3-20", "3–20"),
                ],
                default="",
                max_length=16,
                verbose_name="Внутренний Ø, мм",
            ),
        ),
        migrations.RunPython(_migrate_er_g_inner_from_square, migrations.RunPython.noop),
    ]
