# Generated by Django 5.2.13 on 2026-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0091_product_card_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_workpiece_type',
            field=models.CharField(blank=True, choices=[('preparatory', 'Заготовительный'), ('laser', 'Лазерный'), ('pki', 'ПКИ')], default='', max_length=20, verbose_name='Вид заготовки (карточка)'),
        ),
    ]
