# Generated by Django 5.2.13 on 2026-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0097_printform_page_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='store_link',
            field=models.URLField(blank=True, max_length=2048, verbose_name='Ссылка на магазин'),
        ),
    ]
