# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0099_productsetuptoolrow_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageLoadDiagnostic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Когда")),
                (
                    "source",
                    models.CharField(
                        choices=[("client", "Браузер"), ("server", "Сервер")],
                        db_index=True,
                        max_length=8,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="Пользователь"),
                ),
                ("page_path", models.CharField(db_index=True, max_length=500, verbose_name="Страница")),
                ("server_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="Сервер, мс")),
                ("ttfb_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="TTFB, мс")),
                ("dom_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="DOM, мс")),
                ("load_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="Load, мс")),
                ("is_mobile", models.BooleanField(default=False, verbose_name="Мобильный")),
                ("user_agent", models.CharField(blank=True, default="", max_length=300, verbose_name="User-Agent")),
                (
                    "connection_type",
                    models.CharField(blank=True, default="", max_length=16, verbose_name="Сеть"),
                ),
                ("diagnosis", models.CharField(max_length=500, verbose_name="Подсказка")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Детали")),
            ],
            options={
                "verbose_name": "Диагностика загрузки",
                "verbose_name_plural": "Диагностика загрузок",
                "ordering": ("-created_at", "-id"),
            },
        ),
    ]
