# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0100_pageload_diagnostic"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryWatchTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=200, verbose_name="Аккаунт")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("category", models.CharField(max_length=20, verbose_name="Тип инструмента")),
                ("group_field", models.CharField(max_length=40, verbose_name="Поле группировки")),
                ("group_value", models.CharField(max_length=80, verbose_name="Значение")),
                ("min_qty", models.PositiveSmallIntegerField(default=5, verbose_name="Минимум, шт.")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активно")),
                ("notes", models.CharField(blank=True, default="", max_length=255, verbose_name="Заметка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Контроль остатков (шаблон)",
                "verbose_name_plural": "Контроль остатков (шаблоны)",
                "ordering": ("sort_order", "name", "id"),
            },
        ),
    ]
