# Generated by Django 5.2.13 on 2026-07-12 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0101_inventorywatchtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorywatchtemplate',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги')], max_length=20, verbose_name='Тип инструмента'),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('inventory_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Инвентарный код')),
                ('fixture_type', models.CharField(choices=[('clamp', 'Тиски'), ('base', 'Плита / основание'), ('pad', 'Подкладка'), ('adapter', 'Переходник'), ('gauge', 'Контрольная оснастка'), ('up', 'УП'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип')),
                ('source', models.CharField(choices=[('purchased', 'Покупная'), ('manufactured', 'Изготовленная')], default='purchased', max_length=20, verbose_name='Происхождение')),
                ('status', models.CharField(choices=[('in_stock', 'На складе'), ('in_use', 'В работе'), ('maintenance', 'Ремонт'), ('retired', 'Списана')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Место хранения')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('photo', models.FileField(blank=True, upload_to='fixtures/photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('manufacturing_product', models.ForeignKey(blank=True, help_text='Для изготовленной оснастки — ссылка на карточку в «Наладках».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_manufacturing_cards', to='shifts.product', verbose_name='Карточка изготовления (наладка)')),
            ],
            options={
                'verbose_name': 'Оснастка',
                'verbose_name_plural': 'Оснастка',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductSetupFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('clamp', 'Тиски'), ('base', 'Плита / основание'), ('pad', 'Подкладка'), ('adapter', 'Переходник'), ('gauge', 'Контрольная оснастка'), ('up', 'УП'), ('other', 'Другое')], default='', max_length=20, verbose_name='Роль в установке')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_links', to='shifts.fixture', verbose_name='Оснастка')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_fixtures', to='shifts.productsetup', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Оснастка установки',
                'verbose_name_plural': 'Оснастка установок',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('setup', 'fixture'), name='uniq_setup_fixture_link')],
            },
        ),
    ]
