# Generated by Django 5.2.13 on 2026-07-12 03:31

import django.db.models.deletion
from django.db import migrations, models


def mark_fixture_setup_cards(apps, schema_editor):
    Product = apps.get_model("shifts", "Product")
    Fixture = apps.get_model("shifts", "Fixture")
    fixture_product_ids = set(
        Fixture.objects.exclude(manufacturing_product_id__isnull=True).values_list(
            "manufacturing_product_id", flat=True
        )
    )
    if fixture_product_ids:
        Product.objects.filter(pk__in=fixture_product_ids).update(card_kind="fixture")
    prefix = "[Оснастка]"
    for row in Product.objects.filter(name__startswith=prefix).only("pk", "name"):
        Product.objects.filter(pk=row.pk).update(card_kind="fixture")
        cleaned = (row.name or "").removeprefix(prefix).strip()
        if cleaned and cleaned != row.name:
            Product.objects.filter(pk=row.pk).update(name=cleaned[:300])


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0102_fixture_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_kind',
            field=models.CharField(choices=[('product', 'Изделие'), ('fixture', 'Наладка изготовления оснастки')], db_index=True, default='product', max_length=20, verbose_name='Тип карточки'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='manufacturing_product',
            field=models.ForeignKey(blank=True, help_text='Только карточки из раздела «Оснастка → Наладки изготовления», не из списка изделий.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_manufacturing_cards', to='shifts.product', verbose_name='Наладка изготовления'),
        ),
        migrations.RunPython(mark_fixture_setup_cards, migrations.RunPython.noop),
    ]
