# Generated by Django 5.2.13 on 2026-07-12 03:38

from django.db import migrations


def delete_fixture_setup_products(apps, schema_editor):
    Product = apps.get_model("shifts", "Product")
    Product.objects.filter(card_kind="fixture").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0103_product_card_kind"),
    ]

    operations = [
        migrations.RunPython(delete_fixture_setup_products, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ProductSetupFixture",
        ),
        migrations.DeleteModel(
            name="Fixture",
        ),
        migrations.RemoveField(
            model_name="product",
            name="card_kind",
        ),
    ]
