# Generated by Django 5.2.13 on 2026-07-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0104_remove_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_section',
            field=models.CharField(choices=[('naladki', 'Наладки'), ('osnastka', 'Оснастки')], db_index=True, default='naladki', max_length=20, verbose_name='Раздел каталога'),
        ),
    ]
