# Generated by Django 5.2.13 on 2026-07-12 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0106_product_osnastka_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInspectionDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Размер')),
                ('nominal', models.CharField(blank=True, max_length=80, verbose_name='Номинал')),
                ('tolerance_plus', models.CharField(blank=True, max_length=40, verbose_name='Допуск +')),
                ('tolerance_minus', models.CharField(blank=True, max_length=40, verbose_name='Допуск −')),
                ('tolerance_display', models.CharField(blank=True, help_text='Например ±0.05 или +0.1/-0.05', max_length=80, verbose_name='Допуск (отображение)')),
                ('criticality', models.CharField(choices=[('critical', 'Критичный — каждая деталь'), ('standard', 'Обычный — выборочно'), ('reference', 'Справочный — первая / после переналадки')], default='standard', max_length=20, verbose_name='Критичность')),
                ('frequency', models.CharField(choices=[('always', 'Каждая деталь'), ('every_n', 'Каждая N-я деталь'), ('first_only', 'Только первая / после переналадки')], default='always', max_length=20, verbose_name='Частота контроля')),
                ('frequency_n', models.PositiveSmallIntegerField(default=5, verbose_name='N для выборочного')),
                ('pdf_page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Страница PDF')),
                ('mark_x', models.FloatField(blank=True, null=True, verbose_name='Метка X, %')),
                ('mark_y', models.FloatField(blank=True, null=True, verbose_name='Метка Y, %')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_dimensions', to='shifts.product', verbose_name='Изделие')),
                ('setup', models.ForeignKey(blank=True, help_text='Пусто — контроль на уровне изделия (вкладка «Изделие»).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_dimensions', to='shifts.productsetup', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Контролируемый размер',
                'verbose_name_plural': 'Контролируемые размеры',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductInspectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField(default=1, verbose_name='№ акта')),
                ('inspector_emp_code', models.CharField(blank=True, max_length=32, verbose_name='Таб. №')),
                ('inspector_label', models.CharField(max_length=240, verbose_name='Контролёр')),
                ('part_label', models.CharField(blank=True, help_text='Номер детали, партии или серии.', max_length=120, verbose_name='Деталь / партия')),
                ('author_username', models.CharField(max_length=150, verbose_name='Автор записи')),
                ('result', models.CharField(choices=[('ok', 'Годна'), ('partial', 'Частично'), ('nok', 'Брак')], default='ok', max_length=20, verbose_name='Итог')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='shifts.product', verbose_name='Изделие')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='shifts.productsetup', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Акт контрольных замеров',
                'verbose_name_plural': 'Акты контрольных замеров',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProductInspectionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_label', models.CharField(max_length=120, verbose_name='Размер')),
                ('nominal', models.CharField(blank=True, max_length=80, verbose_name='Номинал')),
                ('tolerance_display', models.CharField(blank=True, max_length=80, verbose_name='Допуск')),
                ('criticality', models.CharField(blank=True, max_length=20, verbose_name='Критичность')),
                ('actual_value', models.CharField(blank=True, max_length=80, verbose_name='Факт')),
                ('is_ok', models.BooleanField(null=True, verbose_name='В допуске')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_values', to='shifts.productinspectiondimension', verbose_name='Размер (карта)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shifts.productinspectionsession', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Замер в акте',
                'verbose_name_plural': 'Замеры в акте',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
