# Generated by Django 5.2.13 on 2026-07-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0107_product_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinspectionvalue',
            name='mark_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Метка X, %'),
        ),
        migrations.AddField(
            model_name='productinspectionvalue',
            name='mark_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Метка Y, %'),
        ),
        migrations.AddField(
            model_name='productinspectionvalue',
            name='pdf_page',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Страница PDF'),
        ),
    ]
