# Generated by Django 5.2.13 on 2026-07-23 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0109_productsetuppiecenorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('shelves', models.PositiveSmallIntegerField(default=4, verbose_name='Число полок')),
                ('columns', models.PositiveSmallIntegerField(default=3, verbose_name='Число столбцов')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Визуальный шкаф',
                'verbose_name_plural': 'Визуальные шкафы',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VisualContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.PositiveSmallIntegerField(verbose_name='Полка (сверху = 1)')),
                ('column', models.PositiveSmallIntegerField(verbose_name='Столбец (слева = 1)')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет метки')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shifts.visualcabinet', verbose_name='Шкаф')),
            ],
            options={
                'verbose_name': 'Контейнер визуального склада',
                'verbose_name_plural': 'Контейнеры визуального склада',
                'ordering': ('shelf', 'column', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VisualContainerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Что лежит')),
                ('tool_category', models.CharField(blank=True, choices=[('', '—'), ('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги')], default='', max_length=20, verbose_name='Категория склада')),
                ('diameter_from_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ø от, мм')),
                ('diameter_to_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ø до, мм')),
                ('quantity_note', models.CharField(blank=True, default='', max_length=80, verbose_name='Кол-во (заметка)')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shifts.visualcontainer', verbose_name='Контейнер')),
                ('tool_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_placements', to='shifts.toolitem', verbose_name='Позиция склада')),
            ],
            options={
                'verbose_name': 'Содержимое контейнера',
                'verbose_name_plural': 'Содержимое контейнеров',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='visualcontainer',
            constraint=models.UniqueConstraint(fields=('cabinet', 'shelf', 'column'), name='uniq_visual_container_cell'),
        ),
    ]
