# Generated by Django 5.2.13 on 2026-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0110_visual_warehouse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visualcontainer',
            name='uniq_visual_container_cell',
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='col_span',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ширина (ячеек)'),
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='row_span',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Высота (полок)'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='color',
            field=models.CharField(blank=True, default='#e74c3c', max_length=7, verbose_name='Цвет'),
        ),
    ]
