# Generated by Django 5.2.13 on 2026-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0111_visual_container_spans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualcontainer',
            options={'ordering': ('shelf', 'stack', 'column', 'id'), 'verbose_name': 'Контейнер визуального склада', 'verbose_name_plural': 'Контейнеры визуального склада'},
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='stack',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Слой на полке (1 = верхний)'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='column',
            field=models.PositiveSmallIntegerField(verbose_name='Позиция слева (1…)'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='row_span',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Высота (полок, устар.)'),
        ),
    ]
