# Generated by Django 5.2.13 on 2026-07-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0112_visual_container_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcontainer',
            name='last_audited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя инвентаризация'),
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='last_audited_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Кто проверял'),
        ),
        migrations.AlterField(
            model_name='inventorystockevent',
            name='event_type',
            field=models.CharField(choices=[('tool_edit', 'Редактирование позиции'), ('tool_delete', 'Удаление позиции'), ('rollback', 'Откат движения'), ('privilege_stock', 'Право на склад'), ('container_audit', 'Инвентаризация ящика')], max_length=24, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='VisualContainerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audited_by', models.CharField(max_length=120, verbose_name='Кто проверял')),
                ('audited_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Примечание к проверке')),
                ('changes_count', models.PositiveIntegerField(default=0, verbose_name='Изменений')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='shifts.visualcontainer', verbose_name='Контейнер')),
            ],
            options={
                'verbose_name': 'Инвентаризация ящика',
                'verbose_name_plural': 'Инвентаризации ящиков',
                'ordering': ('-audited_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='VisualContainerAuditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.PositiveIntegerField(verbose_name='Ожидалось')),
                ('counted_qty', models.PositiveIntegerField(verbose_name='Факт')),
                ('delta', models.IntegerField(default=0, verbose_name='Разница')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('ok', 'Без изменений'), ('adjusted', 'Скорректировано')], default='ok', max_length=16, verbose_name='Статус')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shifts.visualcontaineraudit', verbose_name='Проверка')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_audit_lines', to='shifts.stockmovement', verbose_name='Движение склада')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_audit_lines', to='shifts.toolitem', verbose_name='Инструмент')),
            ],
            options={
                'verbose_name': 'Строка инвентаризации ящика',
                'verbose_name_plural': 'Строки инвентаризации ящиков',
                'ordering': ('id',),
            },
        ),
    ]
