# Generated by Django 5.2.13 on 2026-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0117_visual_organizer_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcontaineritem',
            name='collet_type',
            field=models.CharField(blank=True, choices=[('', 'Все типы'), ('er', 'ER'), ('er_g', 'ER G'), ('ers', 'ERS'), ('eoc', 'EOC'), ('sc', 'SC'), ('sk', 'SK'), ('threading', 'Резьбонарезная'), ('cc', 'CC'), ('dc', 'DC'), ('phc_hc', 'PHC/HC'), ('ter', 'TER')], default='', max_length=16, verbose_name='Тип цанги'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='countersink_type',
            field=models.CharField(blank=True, choices=[('', 'Все типы'), ('hand', 'Ручной'), ('machine', 'Машинный')], default='', max_length=16, verbose_name='Тип зенкера'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='size_label',
            field=models.CharField(blank=True, default='', help_text='Например M6 — фильтр по размеру на складе', max_length=32, verbose_name='Размер (метчик)'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='tap_type',
            field=models.CharField(blank=True, choices=[('', 'Все типы'), ('cutting', 'Режущий метчик'), ('forming', 'Метчик-раскатник'), ('thread_mill', 'Резьбофреза')], default='', max_length=20, verbose_name='Тип резьбового'),
        ),
    ]
