# Generated by Django 5.2.13 on 2026-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0118_visualcontaineritem_tool_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcontaineritem',
            name='hole_type',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('through', 'Сквозное'), ('blind', 'Глухое'), ('any', 'Универсальное')], default='', max_length=16, verbose_name='Отверстие (метчик)'),
        ),
    ]
