# Generated by Django 5.2.13 on 2026-08-30 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0123_visualcontaineritem_rule_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcontaineritem',
            name='body_cutter_type',
            field=models.CharField(blank=True, choices=[('', 'Все типы'), ('face', 'Торцевые насадные'), ('end', 'Концевые'), ('chamfer', 'Фасочные'), ('high_speed', 'Высокоскоростные'), ('round_insert', 'С круглыми пластинами'), ('disc', 'Дисковые'), ('ball', 'Сферические'), ('modular_head', 'Фрезерные головки')], default='', max_length=20, verbose_name='Тип корпусной фрезы'),
        ),
        migrations.AlterField(
            model_name='inventorywatchtemplate',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент')], max_length=20, verbose_name='Тип инструмента'),
        ),
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='visualcontaineritem',
            name='tool_category',
            field=models.CharField(blank=True, choices=[('', '—'), ('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент')], default='', max_length=20, verbose_name='Категория склада'),
        ),
        migrations.CreateModel(
            name='BodyToolSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('indexable_mill', 'Фрезы со сменными пластинами')], default='indexable_mill', max_length=24, verbose_name='Семейство')),
                ('cutter_type', models.CharField(choices=[('face', 'Торцевые насадные'), ('end', 'Концевые'), ('chamfer', 'Фасочные'), ('high_speed', 'Высокоскоростные'), ('round_insert', 'С круглыми пластинами'), ('disc', 'Дисковые'), ('ball', 'Сферические'), ('modular_head', 'Фрезерные головки')], default='face', max_length=20, verbose_name='Тип фрезы')),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Диаметр резания, мм')),
                ('overall_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Общая длина, мм')),
                ('cutting_length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Глубина / ширина резания, мм')),
                ('teeth_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число зубьев / пластин')),
                ('coupling', models.CharField(blank=True, choices=[('', '—'), ('bore', 'Насадные (отверстие)'), ('shank', 'Хвостовик'), ('modular', 'Модульная головка')], default='', max_length=16, verbose_name='Крепление')),
                ('approach_angle_deg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Угол подхода, °')),
                ('size_label', models.CharField(blank=True, default='', max_length=64, verbose_name='Артикул / обозначение')),
                ('insert_compat', models.CharField(blank=True, default='', max_length=80, verbose_name='Совместимые пластины')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_tool_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры корпусного инструмента',
                'verbose_name_plural': 'Параметры корпусного инструмента',
            },
        ),
    ]
