# Generated by Django 5.2.13 on 2026-08-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0124_body_tool_indexable_mill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytoolspec',
            name='insert_family',
            field=models.CharField(blank=True, choices=[('', '— не указано —'), ('APKT', 'APKT — пластина 80°'), ('APMT', 'APMT'), ('APHT', 'APHT'), ('ADKT', 'ADKT'), ('SEKT', 'SEKT'), ('SEHT', 'SEHT'), ('SNHT', 'SNHT'), ('SPGT', 'SPGT'), ('SPHT', 'SPHT'), ('RPMT', 'RPMT'), ('R390', 'R390'), ('CNMG', 'CNMG (токарная)'), ('WNMG', 'WNMG (токарная)'), ('TNMG', 'TNMG (токарная)'), ('SNMG', 'SNMG (токарная)'), ('CCMT', 'CCMT'), ('DCMT', 'DCMT'), ('VCMT', 'VCMT'), ('OTHER', 'Другое')], default='', help_text='Семейство СМП под корпус (APKT, SEKT…)', max_length=24, verbose_name='Тип пластины'),
        ),
    ]
