# Generated by Django 5.2.13 on 2026-09-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0135_visual_container_item_thread_kind_insert_compat'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualcontaineritem',
            name='angle_deg',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Угол, °'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='body_family',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('indexable_mill', 'Фрезы со сменными пластинами')], default='', max_length=32, verbose_name='Семейство корпусного'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='collet_er_size',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Размер ER'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='coolant_filter',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('1', 'Есть'), ('0', 'Нет')], default='', max_length=1, verbose_name='Каналы СОЖ'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='corner_radius_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Радиус, мм'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='flutes_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кромки / зубья'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='insert_family',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('APKT', 'APKT — пластина 80°'), ('APMT', 'APMT'), ('APHT', 'APHT'), ('ADKT', 'ADKT'), ('SEKT', 'SEKT'), ('SEHT', 'SEHT'), ('SNHT', 'SNHT'), ('SPGT', 'SPGT'), ('SPHT', 'SPHT'), ('RPMT', 'RPMT'), ('R390', 'R390'), ('CNMG', 'CNMG (токарная)'), ('WNMG', 'WNMG (токарная)'), ('TNMG', 'TNMG (токарная)'), ('SNMG', 'SNMG (токарная)'), ('CCMT', 'CCMT'), ('DCMT', 'DCMT'), ('VCMT', 'VCMT'), ('OTHER', 'Другое')], default='', max_length=24, verbose_name='Семейство пластины'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='insert_shape',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('C', 'C — ромб 80°'), ('D', 'D — ромб 55°'), ('H', 'H — шестигранник'), ('K', 'K — параллелограмм 55°'), ('L', 'L — прямоугольник'), ('M', 'M — ромб 86°'), ('O', 'O — восьмиугольник'), ('P', 'P — пятиугольник'), ('R', 'R — круглая'), ('S', 'S — квадрат'), ('T', 'T — треугольник'), ('V', 'V — ромб 35°'), ('W', 'W — треугольник 80° (W)')], default='', max_length=8, verbose_name='Форма пластины'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='mount_thread',
            field=models.CharField(blank=True, choices=[('', '—'), ('M6', 'М6'), ('M8', 'М8'), ('M10', 'М10'), ('M12', 'М12'), ('M16', 'М16'), ('M20', 'М20')], default='', max_length=8, verbose_name='Резьба крепления'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='pitch_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Шаг резьбы, мм'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='shank_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('mt3', 'МТ3'), ('mt4', 'МТ4'), ('weldon', 'Weldon'), ('bore', 'Отверстие (насадная)'), ('cylindrical', 'Цилиндрический')], default='', max_length=16, verbose_name='Хвостовик'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='teeth_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число зубьев Z'),
        ),
        migrations.AddField(
            model_name='visualcontaineritem',
            name='thread_standard',
            field=models.CharField(blank=True, choices=[('', 'Все'), ('metric', 'Метрическая (M)'), ('unc', 'UNC'), ('unf', 'UNF'), ('unef', 'UNEF'), ('bsp', 'BSP'), ('npt', 'NPT'), ('other', 'Другое')], default='', max_length=20, verbose_name='Стандарт резьбы'),
        ),
        migrations.AlterField(
            model_name='visualcontaineritem',
            name='body_cutter_type',
            field=models.CharField(blank=True, choices=[('', 'Все типы'), ('face', 'Торцевые насадные фрезы'), ('end', 'Концевые насадные фрезы'), ('chamfer', 'Фасочные фрезы'), ('high_speed', 'Высокоскоростные фрезы'), ('round_insert', 'Фрезы с круглыми пластинами'), ('disc', 'Дисковые фрезы'), ('ball', 'Сферические фрезы'), ('modular_head', 'Фрезерные головки с пластинами')], default='', max_length=20, verbose_name='Тип корпусной фрезы'),
        ),
    ]
