# Generated by Django 5.2.13 on 2026-09-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0137_productsetup_readiness_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип склада',
                'verbose_name_plural': 'Типы склада',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockToolSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.SlugField(max_length=64, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='shifts.stocktooltype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Подтип склада',
                'verbose_name_plural': 'Подтипы склада',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockToolField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, verbose_name='Код поля')),
                ('label', models.CharField(max_length=120, verbose_name='Подпись')),
                ('field_kind', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('select', 'Список'), ('bool', 'Да / нет')], default='text', max_length=16, verbose_name='Вид поля')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Варианты списка')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('unit', models.CharField(blank=True, default='', max_length=24, verbose_name='Ед. изм.')),
                ('help_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Подсказка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtype', models.ForeignKey(blank=True, help_text='Пусто = общая характеристика типа (для всех подтипов)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shifts.stocktoolsubtype', verbose_name='Подтип')),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='shifts.stocktooltype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Характеристика типа склада',
                'verbose_name_plural': 'Характеристики типов склада',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='stocktoolsubtype',
            constraint=models.UniqueConstraint(fields=('tool_type', 'code'), name='uniq_stock_tool_subtype_code'),
        ),
        migrations.AddConstraint(
            model_name='stocktoolfield',
            constraint=models.UniqueConstraint(condition=models.Q(('subtype__isnull', True)), fields=('tool_type', 'key'), name='uniq_stock_tool_field_type_key'),
        ),
        migrations.AddConstraint(
            model_name='stocktoolfield',
            constraint=models.UniqueConstraint(condition=models.Q(('subtype__isnull', False)), fields=('subtype', 'key'), name='uniq_stock_tool_field_subtype_key'),
        ),
    ]
