# Generated by Django 5.2.13 on 2026-09-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0142_seed_extra_stock_tool_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Зона визуального склада',
                'verbose_name_plural': 'Зоны визуального склада',
                'ordering': ('sort_order', 'code', 'id'),
            },
        ),
        migrations.AddField(
            model_name='toolitem',
            name='warehouse_address',
            field=models.CharField(blank=True, default='', help_text='Зона-полка-место, например A-01-02', max_length=32, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Зона-полка-место, например A-01-02', max_length=32, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='shelf',
            field=models.PositiveSmallIntegerField(verbose_name='Полка (сверху = 1, отображение снизу вверх)'),
        ),
        migrations.AddField(
            model_name='visualcabinet',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinets', to='shifts.visualzone', verbose_name='Зона'),
        ),
    ]
