# Generated by Django 5.2.13 on 2026-09-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0144_cabinet_code_remove_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorywatchtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                ],
                max_length=20,
                verbose_name="Тип инструмента",
            ),
        ),
        migrations.AlterField(
            model_name="toolitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="tool_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                ],
                default="",
                max_length=20,
                verbose_name="Категория склада",
            ),
        ),
        migrations.CreateModel(
            name="ReamerSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Диаметр D, мм",
                    ),
                ),
                (
                    "overall_length_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Длина L, мм",
                    ),
                ),
                (
                    "cutting_length_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Длина реж. части Lc, мм",
                    ),
                ),
                (
                    "accuracy_class",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Например H7, H8, IT8…",
                        max_length=24,
                        verbose_name="Класс точности / квалитет",
                    ),
                ),
                (
                    "flutes_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество зубьев Z",
                    ),
                ),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reamer_spec",
                        to="shifts.toolitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметры развертки",
                "verbose_name_plural": "Параметры разверток",
            },
        ),
    ]
