# Generated by Django 5.2.13 on 2026-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0150_normalize_tool_names_metric_comma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodytoolspec",
            name="cutter_type",
            field=models.CharField(
                choices=[
                    ("face", "Торцевые насадные фрезы"),
                    ("end", "Концевые фрезы"),
                    ("chamfer", "Фасочные фрезы"),
                    ("high_speed", "Высокоскоростные фрезы"),
                    ("round_insert", "Фрезы с круглыми пластинами"),
                    ("disc", "Дисковые фрезы"),
                    ("ball", "Сферические фрезы"),
                    ("modular_head", "Фрезерные головки с пластинами"),
                ],
                default="face",
                max_length=20,
                verbose_name="Тип фрезы",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="body_cutter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Все типы"),
                    ("face", "Торцевые насадные фрезы"),
                    ("end", "Концевые фрезы"),
                    ("chamfer", "Фасочные фрезы"),
                    ("high_speed", "Высокоскоростные фрезы"),
                    ("round_insert", "Фрезы с круглыми пластинами"),
                    ("disc", "Дисковые фрезы"),
                    ("ball", "Сферические фрезы"),
                    ("modular_head", "Фрезерные головки с пластинами"),
                ],
                default="",
                max_length=20,
                verbose_name="Тип корпусной фрезы",
            ),
        ),
    ]
