# Generated by Django 5.2.13 on 2026-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0157_remove_insert_kind_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodytoolspec",
            name="cutter_type",
            field=models.CharField(
                choices=[
                    ("end", "Концевая"),
                    ("chamfer", "Фасочная"),
                    ("high_speed", "Высокоскоростная"),
                    ("disc", "Т-образная"),
                    ("ball", "Сферическая"),
                    ("face", "Торцевая"),
                    ("round_insert", "С круглыми пластинами"),
                    ("modular_head", "Модульная головка"),
                ],
                default="end",
                max_length=20,
                verbose_name="Тип фрезы",
            ),
        ),
        migrations.AlterField(
            model_name="bodytoolspec",
            name="shank_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("bore", "Насадная"),
                    ("cylindrical", "Цилиндрическая"),
                    ("weldon", "Weldon"),
                    ("mt3", "МТ3"),
                    ("mt4", "МТ4"),
                ],
                default="",
                max_length=16,
                verbose_name="Тип хвостовика",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="body_cutter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Все типы"),
                    ("end", "Концевая"),
                    ("chamfer", "Фасочная"),
                    ("high_speed", "Высокоскоростная"),
                    ("disc", "Т-образная"),
                    ("ball", "Сферическая"),
                    ("face", "Торцевая"),
                    ("round_insert", "С круглыми пластинами"),
                    ("modular_head", "Модульная головка"),
                ],
                default="",
                max_length=20,
                verbose_name="Тип корпусной фрезы",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="shank_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("bore", "Насадная"),
                    ("cylindrical", "Цилиндрическая"),
                    ("weldon", "Weldon"),
                    ("mt3", "МТ3"),
                    ("mt4", "МТ4"),
                ],
                default="",
                max_length=16,
                verbose_name="Хвостовик",
            ),
        ),
    ]
