# Generated by Django 5.2.13 on 2026-09-14 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0158_body_tool_unified_labels_and_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorywatchtemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                    ("tool_extension", "Удлинители"),
                ],
                max_length=20,
                verbose_name="Тип инструмента",
            ),
        ),
        migrations.AlterField(
            model_name="toolitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                    ("tool_extension", "Удлинители"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="tool_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("end_mill", "Фрезы"),
                    ("tap", "Резьбовой инструмент"),
                    ("center_drill", "Центровки"),
                    ("countersink", "Зенкера"),
                    ("drill", "Сверла"),
                    ("reamer", "Развертки"),
                    ("insert", "Пластинки"),
                    ("collet", "Цанги"),
                    ("body_tool", "Корпусной инструмент"),
                    ("tool_extension", "Удлинители"),
                ],
                default="",
                max_length=20,
                verbose_name="Категория склада",
            ),
        ),
        migrations.CreateModel(
            name="ToolExtensionSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Бренд"
                    ),
                ),
                (
                    "clamp_type",
                    models.CharField(
                        choices=[
                            ("collet", "Цанговый"),
                            ("side_clamp", "Боковая фиксация"),
                            ("thermal", "Термо"),
                        ],
                        default="collet",
                        max_length=16,
                        verbose_name="Зажим",
                    ),
                ),
                (
                    "compatible_parts",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Для цангового — цанги; для боковой/термо — винты",
                        max_length=120,
                        verbose_name="Подходящие цанги / винты",
                    ),
                ),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_extension_spec",
                        to="shifts.toolitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметры удлинителя",
                "verbose_name_plural": "Параметры удлинителей",
            },
        ),
    ]
