# Generated by Django 5.2.13 on 2026-09-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0159_tool_extension_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodytoolspec",
            name="cutter_type",
            field=models.CharField(
                choices=[
                    ("end", "Концевая"),
                    ("chamfer", "Фасочная"),
                    ("high_speed", "Высокоскоростная"),
                    ("disc", "Т-образная"),
                    ("ball", "Сферическая"),
                    ("thread", "Резьбовая"),
                    ("face", "Торцевая"),
                    ("round_insert", "С круглыми пластинами"),
                    ("modular_head", "Модульная головка"),
                ],
                default="end",
                max_length=20,
                verbose_name="Тип фрезы",
            ),
        ),
        migrations.AlterField(
            model_name="visualcontaineritem",
            name="body_cutter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Все типы"),
                    ("end", "Концевая"),
                    ("chamfer", "Фасочная"),
                    ("high_speed", "Высокоскоростная"),
                    ("disc", "Т-образная"),
                    ("ball", "Сферическая"),
                    ("thread", "Резьбовая"),
                    ("face", "Торцевая"),
                    ("round_insert", "С круглыми пластинами"),
                    ("modular_head", "Модульная головка"),
                ],
                default="",
                max_length=20,
                verbose_name="Тип корпусной фрезы",
            ),
        ),
    ]
