# Generated by Django 5.2.13 on 2026-09-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0161_normalize_metric_size_label_prefix_m"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolextensionspec",
            name="overall_length_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Общая длина L, мм",
            ),
        ),
    ]
