# Generated by Django 5.2.13 on 2026-09-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0162_tool_extension_overall_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolextensionspec",
            name="inner_diameter_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Для термо и боковой фиксации",
                max_digits=7,
                null=True,
                verbose_name="Внутренний диаметр Dвн, мм",
            ),
        ),
    ]
