# Generated by Django 5.2.13 on 2026-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0164_tool_extension_inner_diameter_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="drillspec",
            name="shank_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Конус Морзе, цилиндрический или Weldon",
                max_length=24,
                verbose_name="Хвостовик",
            ),
        ),
    ]
