# Generated by Django 5.2.13 on 2026-09-17 19:34

import django.db.models.deletion
from django.db import migrations, models


def seed_sections_and_levels(apps, schema_editor):
    VisualCabinet = apps.get_model("shifts", "VisualCabinet")
    VisualCabinetSection = apps.get_model("shifts", "VisualCabinetSection")
    VisualCabinetLevel = apps.get_model("shifts", "VisualCabinetLevel")
    VisualContainer = apps.get_model("shifts", "VisualContainer")

    for cab in VisualCabinet.objects.all():
        if VisualCabinetSection.objects.filter(cabinet_id=cab.id).exists():
            continue
        section = VisualCabinetSection.objects.create(
            cabinet_id=cab.id,
            index=1,
            name="",
            sort_order=0,
        )
        shelves = max(1, int(cab.shelves or 1))
        columns = max(1, int(cab.columns or 1))
        level_by_index = {}
        for i in range(1, shelves + 1):
            lvl = VisualCabinetLevel.objects.create(
                section_id=section.id,
                index=i,
                kind="shelf",
                columns=columns,
            )
            level_by_index[i] = lvl
        for cont in VisualContainer.objects.filter(cabinet_id=cab.id, parent_id__isnull=True):
            shelf = max(1, min(int(cont.shelf or 1), shelves))
            lvl = level_by_index.get(shelf)
            if lvl is None:
                lvl = VisualCabinetLevel.objects.create(
                    section_id=section.id,
                    index=shelf,
                    kind="shelf",
                    columns=columns,
                )
                level_by_index[shelf] = lvl
            VisualContainer.objects.filter(pk=cont.pk).update(level_id=lvl.id, shelf=shelf)
        # Children inherit parent's level
        for cont in VisualContainer.objects.filter(cabinet_id=cab.id, parent_id__isnull=False).select_related():
            parent = VisualContainer.objects.filter(pk=cont.parent_id).first()
            if parent and parent.level_id:
                VisualContainer.objects.filter(pk=cont.pk).update(
                    level_id=parent.level_id,
                    shelf=parent.shelf,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0165_drill_shank_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualCabinetLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Номер сверху (1…)')),
                ('kind', models.CharField(choices=[('shelf', 'Полка'), ('drawer', 'Ящик')], default='shelf', max_length=16, verbose_name='Тип уровня')),
                ('columns', models.PositiveSmallIntegerField(default=3, verbose_name='Мест / ячеек')),
            ],
            options={
                'verbose_name': 'Уровень визуального шкафа',
                'verbose_name_plural': 'Уровни визуального шкафа',
                'ordering': ('index', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='visualcabinet',
            name='columns',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Число столбцов по умолчанию'),
        ),
        migrations.AlterField(
            model_name='visualcabinet',
            name='shelves',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Число полок (устар., синхронизируется с уровнями)'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Буква-полка-место или буква-секция-полка-место', max_length=32, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='visualcontainer',
            name='shelf',
            field=models.PositiveSmallIntegerField(verbose_name='Полка/уровень (сверху = 1; зеркало level.index)'),
        ),
        migrations.AddField(
            model_name='visualcontainer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shifts.visualcabinetlevel', verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='VisualCabinetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Номер слева (1…)')),
                ('name', models.CharField(blank=True, default='', max_length=80, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='shifts.visualcabinet', verbose_name='Шкаф')),
            ],
            options={
                'verbose_name': 'Секция визуального шкафа',
                'verbose_name_plural': 'Секции визуального шкафа',
                'ordering': ('index', 'id'),
            },
        ),
        migrations.AddField(
            model_name='visualcabinetlevel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='shifts.visualcabinetsection', verbose_name='Секция'),
        ),
        migrations.AddConstraint(
            model_name='visualcabinetsection',
            constraint=models.UniqueConstraint(fields=('cabinet', 'index'), name='uniq_vw_section_cabinet_index'),
        ),
        migrations.AddConstraint(
            model_name='visualcabinetlevel',
            constraint=models.UniqueConstraint(fields=('section', 'index'), name='uniq_vw_level_section_index'),
        ),
        migrations.RunPython(seed_sections_and_levels, noop_reverse),
    ]
