# Generated by Django 5.2.13 on 2026-09-18 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0166_visual_cabinet_sections_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Контракт')),
                ('notes', models.CharField(blank=True, default='', max_length=300, verbose_name='Примечание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контракт (производство)',
                'verbose_name_plural': 'Контракты (производство)',
                'ordering': ('sort_order', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkContractPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320, verbose_name='Изделие')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='shifts.workcontract', verbose_name='Контракт')),
            ],
            options={
                'verbose_name': 'Позиция контракта',
                'verbose_name_plural': 'Позиции контрактов',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
