# Generated by Django 5.2.13 on 2026-09-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0167_work_contract_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcontractposition',
            name='stage',
            field=models.CharField(choices=[('not_started', 'Не запущено'), ('n_a', 'не касается'), ('no_info', 'не приехал или нет информации'), ('operation', 'На операции')], default='not_started', max_length=16, verbose_name='Этап'),
        ),
        migrations.CreateModel(
            name='WorkPositionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Операция')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='shifts.workcontractposition', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Операция изделия',
                'verbose_name_plural': 'Операции изделий',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='workcontractposition',
            name='current_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shifts.workpositionoperation', verbose_name='Текущая операция'),
        ),
    ]
