# Generated by Django 5.2.13 on 2026-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0169_work_contract_position_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcontractposition',
            name='stage',
            field=models.CharField(choices=[('not_started', 'Не запущено'), ('n_a', 'не касается'), ('no_info', 'не приехал или нет информации'), ('operation', 'На операции'), ('done', 'Все этапы пройдены'), ('paused', 'Пауза')], default='not_started', max_length=16, verbose_name='Этап'),
        ),
    ]
