# Generated by Django 5.2.13 on 2026-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0171_seed_goz_2026_25_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineLevelingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Серийный номер",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=8,
                        null=True,
                        verbose_name="Вес, кг",
                    ),
                ),
                (
                    "feet_count",
                    models.PositiveSmallIntegerField(
                        choices=[(4, "4"), (6, "6"), (8, "8")],
                        default=8,
                        verbose_name="Число ножек",
                    ),
                ),
                (
                    "foot_layout",
                    models.CharField(
                        choices=[
                            ("rect8", "Прямоугольник 8 (углы + середины)"),
                            ("rect6", "Прямоугольник 6"),
                            ("rect4", "Прямоугольник 4 (углы)"),
                        ],
                        default="rect8",
                        max_length=16,
                        verbose_name="Схема опор",
                    ),
                ),
                (
                    "thread_pitch_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.50",
                        help_text="Сколько мм подъёма за один полный оборот винта/клина",
                        max_digits=5,
                        verbose_name="Шаг резьбы опоры, мм",
                    ),
                ),
                (
                    "table_span_x_mm",
                    models.PositiveIntegerField(
                        default=850,
                        help_text="Длина базы уровня / стола по X",
                        verbose_name="База уровня по X, мм",
                    ),
                ),
                (
                    "table_span_y_mm",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Длина базы уровня / стола по Y",
                        verbose_name="База уровня по Y, мм",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=400, verbose_name="Заметка"
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список объектов: level_x, level_y, corners, ts, author",
                        verbose_name="История замеров",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Кто обновил",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Выставление станка",
                "verbose_name_plural": "Выставление станков",
                "ordering": ("name", "id"),
            },
        ),
    ]
