# Generated by Django 5.2.13 on 2026-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0172_machine_leveling_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinelevelingcard",
            name="bed_length_mm",
            field=models.PositiveIntegerField(
                default=2200,
                help_text="Габарит станины сзади→вперёд к оператору (ось Y)",
                verbose_name="Длина станины Y, мм",
            ),
        ),
        migrations.AddField(
            model_name="machinelevelingcard",
            name="bed_width_mm",
            field=models.PositiveIntegerField(
                default=1200,
                help_text="Габарит станины слева→направо (ось X)",
                verbose_name="Ширина станины X, мм",
            ),
        ),
        migrations.AddField(
            model_name="machinelevelingcard",
            name="feet_positions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{num, x_mm, y_mm}, …]; начало — задний левый угол, X→право, Y→оператор",
                verbose_name="Координаты опор",
            ),
        ),
        migrations.AddField(
            model_name="machinelevelingcard",
            name="workflow",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="stage, tol_mm_m, travel_x, travel_y, done flags",
                verbose_name="Этапы выставления",
            ),
        ),
        migrations.AlterField(
            model_name="machinelevelingcard",
            name="feet_count",
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name="Число ножек"
            ),
        ),
        migrations.AlterField(
            model_name="machinelevelingcard",
            name="foot_layout",
            field=models.CharField(
                choices=[
                    ("custom", "Свои координаты опор"),
                    ("rect8", "Шаблон 8: 1-2-4-5 | 6-7-8-9"),
                    ("rect6", "Шаблон 6"),
                    ("rect4", "Шаблон 4 (углы)"),
                ],
                default="custom",
                max_length=16,
                verbose_name="Схема опор",
            ),
        ),
        migrations.AlterField(
            model_name="machinelevelingcard",
            name="table_span_x_mm",
            field=models.PositiveIntegerField(
                default=850,
                help_text="Длина базы уровня при замере по X",
                verbose_name="База уровня по X, мм",
            ),
        ),
        migrations.AlterField(
            model_name="machinelevelingcard",
            name="table_span_y_mm",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Длина базы уровня при замере по Y",
                verbose_name="База уровня по Y, мм",
            ),
        ),
    ]
