# Generated by Django 5.2.13 on 2026-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0173_machine_leveling_geometry_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpositionoperation',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Подсказка при наведении на этап', max_length=300, verbose_name='Описание'),
        ),
    ]
