# Generated by Django 5.2.13 on 2026-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0174_workpositionoperation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAiTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('username', models.CharField(db_index=True, max_length=120, verbose_name='Кто спросил')),
                ('kind', models.CharField(choices=[('inv_chat', 'Чат склада'), ('setup_ai', 'ИИ-анализ наладки')], db_index=True, max_length=16, verbose_name='Тип')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Сессия')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('reply', models.TextField(blank=True, default='', verbose_name='Ответ')),
                ('error', models.CharField(blank=True, default='', max_length=400, verbose_name='Ошибка')),
                ('ok', models.BooleanField(default=True, verbose_name='Успех')),
                ('used_tools', models.JSONField(blank=True, default=list, verbose_name='Tools')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Реплика ИИ',
                'verbose_name_plural': 'Архив диалогов ИИ',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['-created_at', 'kind'], name='inv_ai_turn_created_kind')],
            },
        ),
    ]
