# Generated by Django 5.2.13 on 2026-09-29 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0179_siteupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorywatchtemplate',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('reamer', 'Развертки'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент'), ('tool_extension', 'Удлинители'), ('gauge_smooth', 'Гладкие калибры'), ('gauge_thread', 'Резьбовые калибры'), ('measure_univ', 'Универсальный измерительный'), ('measure_surf', 'Шероховатость и твёрдость'), ('measure_check', 'Поверочная оснастка'), ('measure_mark', 'Разметочный инструмент')], max_length=20, verbose_name='Тип инструмента'),
        ),
        migrations.AlterField(
            model_name='toolitem',
            name='category',
            field=models.CharField(choices=[('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('reamer', 'Развертки'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент'), ('tool_extension', 'Удлинители'), ('gauge_smooth', 'Гладкие калибры'), ('gauge_thread', 'Резьбовые калибры'), ('measure_univ', 'Универсальный измерительный'), ('measure_surf', 'Шероховатость и твёрдость'), ('measure_check', 'Поверочная оснастка'), ('measure_mark', 'Разметочный инструмент')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='visualcontaineritem',
            name='tool_category',
            field=models.CharField(blank=True, choices=[('', '—'), ('end_mill', 'Фрезы'), ('tap', 'Резьбовой инструмент'), ('center_drill', 'Центровки'), ('countersink', 'Зенкера'), ('drill', 'Сверла'), ('reamer', 'Развертки'), ('insert', 'Пластинки'), ('collet', 'Цанги'), ('body_tool', 'Корпусной инструмент'), ('tool_extension', 'Удлинители'), ('gauge_smooth', 'Гладкие калибры'), ('gauge_thread', 'Резьбовые калибры'), ('measure_univ', 'Универсальный измерительный'), ('measure_surf', 'Шероховатость и твёрдость'), ('measure_check', 'Поверочная оснастка'), ('measure_mark', 'Разметочный инструмент')], default='', max_length=20, verbose_name='Категория склада'),
        ),
        migrations.CreateModel(
            name='MeasuringToolSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=80, verbose_name='Бренд')),
                ('kind', models.CharField(blank=True, choices=[('caliper', 'Штангенциркуль'), ('micrometer', 'Микрометры'), ('bore_gauge', 'Нутромеры'), ('dial_indicator', 'Индикатор часового типа'), ('square', 'Угольники'), ('protractor', 'Угломеры'), ('feeler', 'Щупы'), ('gauge_blocks', 'Концевые меры длины'), ('roughness_sample', 'Образцы шероховатости'), ('profilometer', 'Профилометры'), ('hardness_tester', 'Твердомеры'), ('surface_plate', 'Поверочные плиты'), ('prism', 'Призмы поверочные'), ('sine_table', 'Синусные столы'), ('stand', 'Стойки и штативы'), ('scriber', 'Чертилки'), ('center_punch', 'Кернеры'), ('height_gauge', 'Рейсмасы'), ('marking_compass', 'Разметочные циркули')], default='', max_length=32, verbose_name='Вид')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measuring_tool_spec', to='shifts.toolitem')),
            ],
            options={
                'verbose_name': 'Параметры измерительного',
                'verbose_name_plural': 'Параметры измерительного',
            },
        ),
    ]
