# Generated by Django 5.2.13 on 2026-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0180_measuring_tool_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringtoolspec',
            name='accuracy',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Точность'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='go_nogo',
            field=models.CharField(blank=True, choices=[('go', 'Проходной'), ('nogo', 'Непроходной'), ('set', 'Комплект')], default='', max_length=8, verbose_name='Проходной / непроходной'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='ip_rating',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Степень защиты IP'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='measure_range',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Диапазон'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='pitch_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Шаг, мм'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='thread_size_label',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Размер резьбы'),
        ),
        migrations.AlterField(
            model_name='measuringtoolspec',
            name='kind',
            field=models.CharField(blank=True, choices=[('plug', 'Пробка'), ('ring', 'Кольцо'), ('caliper', 'Штангенциркуль'), ('micrometer', 'Микрометры'), ('bore_gauge', 'Нутромеры'), ('dial_indicator', 'Индикатор часового типа'), ('square', 'Угольники'), ('protractor', 'Угломеры'), ('feeler', 'Щупы'), ('gauge_blocks', 'Концевые меры длины'), ('roughness_sample', 'Образцы шероховатости'), ('profilometer', 'Профилометры'), ('hardness_tester', 'Твердомеры'), ('surface_plate', 'Поверочные плиты'), ('prism', 'Призмы поверочные'), ('sine_table', 'Синусные столы'), ('stand', 'Стойки и штативы'), ('scriber', 'Чертилки'), ('center_punch', 'Кернеры'), ('height_gauge', 'Рейсмасы'), ('marking_compass', 'Разметочные циркули')], default='', max_length=32, verbose_name='Вид'),
        ),
    ]
