# Generated by Django 5.2.13 on 2026-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0182_notebook_measuring_verification_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringtoolspec',
            name='check_accuracy_class',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Класс точности'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='check_size',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='measuringtoolspec',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Длина, мм'),
        ),
    ]
